FFF
======================================================================
FAIL: test_delete_nonexistent (__main__.TestAssignment2.test_delete_nonexistent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/amin/Downloads/CSE 138/Assignment_2/grading/test_assignment2_follower-error.py", line 55, in test_delete_nonexistent
    self.assertEqual(res.status_code, 503, msg='Did not return status 503 (delete non-existent key)')
AssertionError: 500 != 503 : Did not return status 503 (delete non-existent key)

======================================================================
FAIL: test_get_nonexistent (__main__.TestAssignment2.test_get_nonexistent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/amin/Downloads/CSE 138/Assignment_2/grading/test_assignment2_follower-error.py", line 46, in test_get_nonexistent
    self.assertEqual(res.status_code, 503, msg='Did not return status 503 (get non-existent key)')
AssertionError: 500 != 503 : Did not return status 503 (get non-existent key)

======================================================================
FAIL: test_put_get (__main__.TestAssignment2.test_put_get)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/amin/Downloads/CSE 138/Assignment_2/grading/test_assignment2_follower-error.py", line 64, in test_put_get
    self.assertEqual(res.status_code, 503, msg='Did not return status 503 (simple put then get: put)')
AssertionError: 500 != 503 : Did not return status 503 (simple put then get: put)

----------------------------------------------------------------------
Ran 3 tests in 0.042s

FAILED (failures=3)
